let games = [
    {
        'id': 0,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 1,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 2,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 3,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 4,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 5,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 6,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 7,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 8,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 9,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 10,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 11,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
]

let basketProducts = [
    {
        'id': 0,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 1,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
]