let games = [
    {
        'id': 0,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'treilerSrc': "video/IMG_6148.MP4",
        'bigBanner': "img/banners/big.png",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 1,
        'name': "Valorant",
        'link': "",
        'imgH': "img/banners/1.jpg",
        'imgW': "img/banners/a1.jpg",
        'treilerSrc': "video/2.MP4",
        'bigBanner': "img/banners/d5770738dde027118563ae96ae58e7d3.jpg",
        'newPrice': 500,
        'oldPrice': 799,
    },
    {
        'id': 2,
        'name': "Counter Strike 2",
        'link': "",
        'imgH': "img/banners/2.jpg",
        'imgW': "img/banners/a2.jpg",
        'treilerSrc': "video/3.MP4",
        'bigBanner': "img/banners/52nahuy.jpg",
        'newPrice': 679,
        'oldPrice': 800,
    },
    {
        'id': 3,
        'name': "Player Unknowns Buttle Grounds",
        'link': "",
        'imgH': "img/banners/3.jpg",
        'imgW': "img/banners/a3.jpg",
        'treilerSrc': "video/4.MP4",
        'newPrice': 120,
        'oldPrice': 350,
    },
    {
        'id': 4,
        'name': "Ghosts",
        'link': "",
        'imgH': "img/banners/4.jpg",
        'imgW': "img/banners/a4.jpg",
        'treilerSrc': "video/2.MP4",
        'newPrice': 1255,
        'oldPrice': 1600,
    },
    {
        'id': 5,
        'name': "Drill Aviasion",
        'link': "",
        'imgH': "img/banners/5.jpg",
        'imgW': "img/banners/a5.jpg",
        'treilerSrc': "video/4.MP4",
        'newPrice': 3678,
        'oldPrice': 4000,
    },
    {
        'id': 6,
        'name': "ALBLAK 52",
        'link': "",
        'imgH': "img/banners/6.jpg",
        'imgW': "img/banners/a6.jpg",
        'treilerSrc': "video/3.MP4",
        'newPrice': 7952,
        'oldPrice': 8812,
    },
    {
        'id': 7,
        'name': "FRIENDLY THUG 52 NGG",
        'link': "",
        'imgH': "img/banners/7.jpg",
        'imgW': "img/banners/a7.jpg",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 812,
        'oldPrice': 1812,
    },
    {
        'id': 8,
        'name': "YA USTAL PISAT",
        'link': "",
        'imgH': "img/banners/8.jpg",
        'imgW': "img/banners/a8.jpg",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 9,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/9.jpg",
        'imgW': "img/banners/a9.jpg",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 6700,
        'oldPrice': 7000,
    },
    {
        'id': 10,
        'name': "Game Of Mir",
        'link': "",
        'imgH': "img/banners/10.jpg",
        'imgW': "img/banners/a10.jpg",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 4355,
        'oldPrice': 4500,
    },
    {
        'id': 11,
        'name': "On The Run 2",
        'link': "",
        'imgH': "img/banners/11.jpg",
        'imgW': "img/banners/a11.jpg",
        'treilerSrc': "video/IMG_6148.MP4",
        'newPrice': 2344,
        'oldPrice': 3050,
    },
]

let basketProducts = [
    {
        'id': 0,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
    {
        'id': 1,
        'name': "Call Of Duty: Cold War 2",
        'link': "",
        'imgH': "img/banners/farmsim.png",
        'imgW': "img/banners/img1.png",
        'newPrice': 4599,
        'oldPrice': 5120,
    },
]